//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpftest.SalesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesService.SalesServiceSoap")]
    public interface SalesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSales(Wpftest.SalesService.Sale sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSales", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSalesAsync(Wpftest.SalesService.Sale sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SelectSales(Wpftest.SalesService.Sale sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectSales", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SelectSalesAsync(Wpftest.SalesService.Sale sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSalesGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSalesGrade(Wpftest.SalesService.SaleGrade salegrade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSalesGrade", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSalesGradeAsync(Wpftest.SalesService.SaleGrade salegrade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wpftest.SalesService.Month SelectGrade(string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectGrade", ReplyAction="*")]
        System.Threading.Tasks.Task<Wpftest.SalesService.Month> SelectGradeAsync(string year);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sale : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sal_noField;
        
        private string sal_nameField;
        
        private string sal_classField;
        
        private string sal_sexField;
        
        private string sal_ageField;
        
        private string sal_numberField;
        
        private string sal_pwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sal_no {
            get {
                return this.sal_noField;
            }
            set {
                this.sal_noField = value;
                this.RaisePropertyChanged("sal_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sal_name {
            get {
                return this.sal_nameField;
            }
            set {
                this.sal_nameField = value;
                this.RaisePropertyChanged("sal_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sal_class {
            get {
                return this.sal_classField;
            }
            set {
                this.sal_classField = value;
                this.RaisePropertyChanged("sal_class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sal_sex {
            get {
                return this.sal_sexField;
            }
            set {
                this.sal_sexField = value;
                this.RaisePropertyChanged("sal_sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sal_age {
            get {
                return this.sal_ageField;
            }
            set {
                this.sal_ageField = value;
                this.RaisePropertyChanged("sal_age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sal_number {
            get {
                return this.sal_numberField;
            }
            set {
                this.sal_numberField = value;
                this.RaisePropertyChanged("sal_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sal_pwd {
            get {
                return this.sal_pwdField;
            }
            set {
                this.sal_pwdField = value;
                this.RaisePropertyChanged("sal_pwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Month : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string janField;
        
        private string febField;
        
        private string marField;
        
        private string aprField;
        
        private string mayField;
        
        private string junField;
        
        private string julField;
        
        private string augField;
        
        private string sepField;
        
        private string octField;
        
        private string novField;
        
        private string decField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Jan {
            get {
                return this.janField;
            }
            set {
                this.janField = value;
                this.RaisePropertyChanged("Jan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Feb {
            get {
                return this.febField;
            }
            set {
                this.febField = value;
                this.RaisePropertyChanged("Feb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mar {
            get {
                return this.marField;
            }
            set {
                this.marField = value;
                this.RaisePropertyChanged("Mar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apr {
            get {
                return this.aprField;
            }
            set {
                this.aprField = value;
                this.RaisePropertyChanged("Apr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string May {
            get {
                return this.mayField;
            }
            set {
                this.mayField = value;
                this.RaisePropertyChanged("May");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Jun {
            get {
                return this.junField;
            }
            set {
                this.junField = value;
                this.RaisePropertyChanged("Jun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Jul {
            get {
                return this.julField;
            }
            set {
                this.julField = value;
                this.RaisePropertyChanged("Jul");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Aug {
            get {
                return this.augField;
            }
            set {
                this.augField = value;
                this.RaisePropertyChanged("Aug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Sep {
            get {
                return this.sepField;
            }
            set {
                this.sepField = value;
                this.RaisePropertyChanged("Sep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Oct {
            get {
                return this.octField;
            }
            set {
                this.octField = value;
                this.RaisePropertyChanged("Oct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Nov {
            get {
                return this.novField;
            }
            set {
                this.novField = value;
                this.RaisePropertyChanged("Nov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Dec {
            get {
                return this.decField;
            }
            set {
                this.decField = value;
                this.RaisePropertyChanged("Dec");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleGrade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sal_noField;
        
        private string sal_dateField;
        
        private string sal_mountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sal_no {
            get {
                return this.sal_noField;
            }
            set {
                this.sal_noField = value;
                this.RaisePropertyChanged("sal_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sal_date {
            get {
                return this.sal_dateField;
            }
            set {
                this.sal_dateField = value;
                this.RaisePropertyChanged("sal_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sal_mount {
            get {
                return this.sal_mountField;
            }
            set {
                this.sal_mountField = value;
                this.RaisePropertyChanged("sal_mount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesServiceSoapChannel : Wpftest.SalesService.SalesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesServiceSoapClient : System.ServiceModel.ClientBase<Wpftest.SalesService.SalesServiceSoap>, Wpftest.SalesService.SalesServiceSoap {
        
        public SalesServiceSoapClient() {
        }
        
        public SalesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddSales(Wpftest.SalesService.Sale sale) {
            return base.Channel.AddSales(sale);
        }
        
        public System.Threading.Tasks.Task<string> AddSalesAsync(Wpftest.SalesService.Sale sale) {
            return base.Channel.AddSalesAsync(sale);
        }
        
        public string SelectSales(Wpftest.SalesService.Sale sale) {
            return base.Channel.SelectSales(sale);
        }
        
        public System.Threading.Tasks.Task<string> SelectSalesAsync(Wpftest.SalesService.Sale sale) {
            return base.Channel.SelectSalesAsync(sale);
        }
        
        public string AddSalesGrade(Wpftest.SalesService.SaleGrade salegrade) {
            return base.Channel.AddSalesGrade(salegrade);
        }
        
        public System.Threading.Tasks.Task<string> AddSalesGradeAsync(Wpftest.SalesService.SaleGrade salegrade) {
            return base.Channel.AddSalesGradeAsync(salegrade);
        }
        
        public Wpftest.SalesService.Month SelectGrade(string year) {
            return base.Channel.SelectGrade(year);
        }
        
        public System.Threading.Tasks.Task<Wpftest.SalesService.Month> SelectGradeAsync(string year) {
            return base.Channel.SelectGradeAsync(year);
        }
    }
}
